#!/bin/sh
# Auto-generated by cxas-scrapi for local/CI Docker unified execution

AGENT_DIR=$1
PROJECT_ID=$2
LOCATION=${3:-us}

if [ -z "$AGENT_DIR" ] || [ -z "$PROJECT_ID" ]; then
  echo "Usage: $0 <agent_dir> <project_id> [location]"
  exit 1
fi

ADC_FILE_HOST=""

if [ ! -z "$GOOGLE_APPLICATION_CREDENTIALS" ]; then
  ADC_FILE_HOST="$GOOGLE_APPLICATION_CREDENTIALS"
elif [ -f "$HOME/.config/gcloud/application_default_credentials.json" ]; then
  ADC_FILE_HOST="$HOME/.config/gcloud/application_default_credentials.json"
fi

if [ -z "$ADC_FILE_HOST" ]; then
  echo "Error: No application default credentials found."
  echo "Run 'gcloud auth application-default login' locally."
  exit 1
fi

echo "Building Docker Image..."
docker build -t agent-image "$(dirname "$0")/$AGENT_DIR"

echo "Running Docker Container..."
docker run --rm \
  -v "$(dirname "$0")":/workspace \
  -w /workspace \
  -e PROJECT_ID="$PROJECT_ID" \
  -e LOCATION="$LOCATION" \
  -e GOOGLE_CLOUD_PROJECT="$PROJECT_ID" \
  -e GOOGLE_APPLICATION_CREDENTIALS=\
/workspace/application_default_credentials.json \
  -v "$ADC_FILE_HOST":/workspace/application_default_credentials.json \
  agent-image \
  ci-test --app-dir "$AGENT_DIR" \
            --project-id "$PROJECT_ID" \
            --location "$LOCATION" \
            --display-name "[Local] $(basename "$AGENT_DIR")"
